services:
  - type: web
    name: ai-chatbot
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: MODEL_NAME
        value: "distilgpt2"
    buildCommand: |
      python -m pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
