services:
  - type: web
    name: ai-chatbot
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHON_VERSION
        value: "3.11.11"


